version: '3'

services:
  postgres:
    restart: always
    image: postgres:10.3-alpine
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data

  web:
    build: ./docker/web
    ports:
      - "8000:8000"
    working_dir: /project/taxi_api
    volumes:
      - ./backend:/project
#    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    command: "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
