# Generated by Django 2.0.3 on 2018-03-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v0', '0003_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='number',
            field=models.CharField(default='AAA 777', max_length=8),
        ),
    ]
